services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_by_zipcode_api
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure
