### 200 valid CEP
# curl --location 'http://localhost:8080/01001000'
GET http://localhost:8080/01001000

### 404 not found CEP
# curl --location 'http://localhost:8080/99999999'
GET http://localhost:8080/99999999

### 422 invalid CEP
# curl --location 'http://localhost:8080/123456'
GET http://localhost:8080/123456
